fix test failures

diff --git a/solidblocks-cloud-init/src/main/resources/blcks-cloud-init-bootstrap.sh.template b/solidblocks-cloud-init/src/main/resources/blcks-cloud-init-bootstrap.sh.template
--- a/solidblocks-cloud-init/src/main/resources/blcks-cloud-init-bootstrap.sh.template
+++ b/solidblocks-cloud-init/src/main/resources/blcks-cloud-init-bootstrap.sh.template
@@ -122,9 +122,6 @@ function log_die() { log emergency "${*}"; exit 4;}
 ################################################################
 _DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
-test -f "${_DIR}/log.sh" && source "${_DIR}/log.sh"
-test -f "${_DIR}/utils.sh" && source "${_DIR}/utils.sh"
-
 CURL_WRAPPER_RETRY_DELAY=${CURL_WRAPPER_RETRY_DELAY:-5}
 CURL_WRAPPER_RETRIES=${CURL_WRAPPER_RETRIES:-10}
 
@@ -132,7 +129,7 @@ function curl_wrapper() {
     local try=0
     while [ $try -lt ${CURL_WRAPPER_RETRIES} ] && ! curl --retry-connrefused --fail --silent --location --show-error "$@"; do
         try=$((try+1))
-        echo "curl call '$@' (${try}/${CURL_WRAPPER_RETRIES}) failed, retrying in ${CURL_WRAPPER_RETRY_DELAY} seconds"
+        echo "curl call '$@' (${try}/${CURL_WRAPPER_RETRIES}) failed, retrying in ${CURL_WRAPPER_RETRY_DELAY} seconds" 1>&2;
         sleep "${CURL_WRAPPER_RETRY_DELAY}"
     done
 }
